//
// Created by odin on 26/12/18.
//

#ifndef GROUP_AUGMENTATION_CLASSES_H
#define GROUP_AUGMENTATION_CLASSES_H

enum Classes {
    BREEDER, HELPER, FLOATER
};

#endif //GROUP_AUGMENTATION_CLASSES_H
